user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log notice;
pid        /var/log/nginx/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    # Questo include automaticamente i tuoi 3 ambienti dal file default.conf
    include /etc/nginx/conf.d/*.conf; 
}

# SEZIONE DATABASE (TCP) - Richiesta dalla nota tecnica al livello 4
stream {
    server {
        listen 5432;
        # Qui posso aggiungere i vari IP a cui dare l'accesso, per ora accetto le connessioni solo da me stesso
        allow 127.0.0.1;
        # Rifiuto tutte le connessioni provenienti da altri IP
        deny all;
        proxy_pass db:5432;
    }
}